### ISSUE TITLE
Sample data used not found

### ISSUE THREAD

**Issue by jonauq2508** [albinwwells/Raster-Basics#1]
Hi I would like to use the sample data, but the link is down

**Comment by albinwwells** [comment]
Hi,
The sample data used in the examples should be available online following the links provided in the Jupyter notebooks. Just change the download filepath and the rest should be set up correctly. Let me know if you have any questions--sorry for any inconvenience

**Comment by jonauq2508** [comment]
great, thank you so much for your response
